name: Release-Latest

# Controls when the workflow will run

on:
  push:
    branches: [main]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build: 
    uses: ./.github/workflows/ci.yml

  # This workflow contains a single job called "release"
  release:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download resume artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Résumé
          body: "The latest résumé from Fahmi Hidayat"
          fail_on_unmatched_files: true
          files: resume.pdf
